### ISSUE TITLE
Env based auth?

### ISSUE THREAD

**Issue by frioux** [MestreLion/humblebundle#11]
Would you be willing to accept a patch that allows me to put the session cookie in an environment variable?

**Comment by MestreLion** [comment]
I see no problem with that, but... what for? You only have to import it once, as it gets written to the `humblebundle` cookie file at, IIRC, `~/.config/humblebundle/cookies.txt`

**Comment by frioux** [comment]
I didn't know that. I'll verify and if that's the case just close this.

## 

sent from a rotary phone, pardon my brevity
