### ISSUE TITLE
Ability to clear credentials

### ISSUE THREAD

**Issue by xavdid** [MestreLion/humblebundle#23]
While I was tinkering, I decided to change my Humble password to test auth flows and now there's somethings stale that causes 401's whenever I try to update my game info.

It'd be great to have a function (and cli switch) that clears all saved auth data (username/password, cookies, etc) and starts fresh!

**Comment by MestreLion** [comment]
Good call! And it looks like `-C` is still available as a command line option. I'll add a `-C|--clear`, thanks!
