### ISSUE TITLE
Add python3 compatibility

### ISSUE THREAD

**Issue by drakenation** [MestreLion/humblebundle#34]
The app isn't currently compatible with python3. 

Progressbar isn't compatible with python3, switching to [progressbar2](https://pypi.python.org/pypi/progressbar2) might solve this.

Some core libs have also changed, mostly urllib related.

**Comment by MestreLion** [comment]
This is a much-wanted feature indeed, but would require some major changes, which unfortunately I don't have the time to do. But a PR/patch would be very welcome!

Also, If possible, backwards-compability with Python2 is very desired. I presume this will be a pain considering the `urllib` and such changes.

**Comment by chilinux** [comment]
Submitted pull request

**Comment by MestreLion** [comment]
Fixed in PR#40
